### ISSUE TITLE
Logo design for simple painting

### ISSUE THREAD

**Issue by zdesign1** [faimasitumorang/simple-painting-app#1]
Hello, I have created a logo design for this project, do you want it for this project?
![logotype](https://user-images.githubusercontent.com/38174403/38648959-34ae645e-3e1e-11e8-9fc0-f3e5dcc20adc.png)
![logotype1](https://user-images.githubusercontent.com/38174403/38648994-6a330e54-3e1e-11e8-88c6-2321029348e9.png)

**Comment by faimasitumorang** [comment]
Awesome, I like the logo, I want it. Thank u

**Comment by zdesign1** [comment]
Okay, You can download the logo on this link https://drive.google.com/open?id=1Px1b8cxFsfggS4r-D0C7BiJO-4Xs0qVj

**Comment by faimasitumorang** [comment]
Thanks you for the logo, i will close this
